AllCops:
  RunRailsCops: true

  Exclude:
    - "vendor/**/*"
    - "bin/**/*"

Metrics/LineLength:
  Max: 120

Style/ClassAndModuleChildren:
  Enabled: false

Style/Documentation:
  Description: Document classes and non-namespace modules.
  Enabled: false

Style/StringLiterals:
  EnforcedStyle: double_quotes

