scss_files: "app/assets/stylesheets/**/*.scss"

exclude:
  - "vendor/**/*"
  - "coverage/**/*"

linters:
  LeadingZero:
    style: include_zero

  QualifyingElement:
    enabled: true
    # Should this be added back?
    # https://github.com/CSSLint/csslint/wiki/Disallow-unqualified-attribute-selectors
    allow_element_with_attribute: true
    alow_element_with_class: false
    allow_element_with_id: false

  SelectorDepth:
    max_depth: 4

  NestingDepth:
    max_depth: 4

  StringQuotes:
    style: double_quotes

  ColorKeyword:
    enabled: false

  ColorVariable:
    enabled: false
